version: '3'
services:
  postgres:
    image: "postgres" # use latest official postgres version
#    env_file:
#      - database.env # configure postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=testplugindb
      - POSTGRES_USER=Olli
      - POSTGRES_PASSWORD=illO

  mysql:
    image: mysql:5.7
    volumes:
      - mysql-db:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_DATABASE=testplugindb
      - MYSQL_ROOT_PASSWORD=illO
      - MYSQL_USER=Olli
      - MYSQL_PASSWORD=illO

volumes:
  postgres-data: # named volumes can be managed easier using docker-compose
  mysql-db:
