# This is a basic workflow that is manually triggered

name: gh test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    tags:
      - '*.*.*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  bla:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    
    - name: Github bla
      env:
        GH_TOKEN: ${{ github.token }}
        MILESTONE: ${{ github.ref_name }}
      run: |
        echo $MILESTONE
        MILESTONENR=$(gh api /repos/{owner}/{repo}/milestones | jq '.[] | select(.title==env.MILESTONE) | .number')
        echo '{"state": "closed"}' | gh api --method PATCH repos/{owner}/{repo}/milestones/$MILESTONENR --input -
        
