name: Release published - inform issues
on:
  release:
    types: [released] # only releases, no pre-releases

permissions:
  issues: write
  pull-requests: write

jobs:
  Comment:
    runs-on: ubuntu-latest
    steps:
      - uses: bflad/action-milestone-comment@v2
        with:
          body: |
            This functionality has been released in ${{ github.release.tag_name }}.

            For further feature requests or bug reports with this functionality, please create a [new GitHub issue](https://github.com/${{ github.repository }}/issues/new). Thank you!
